In [1]:
import torch

<h4> A tensor is a k-dimension of numerical values.
if k = 1, it is called 'vector', k = 2 it's called matrix, and k > 2 it is just called k-th order tensor. <h4>

In [3]:
# Create tensor with size 12 from 0(gap is 1)
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# If we just want to know the total number of elements in a tensor?
x.numel()

12

In [5]:
# If we want a tensor's shape
x.shape

torch.Size([12])

In [6]:
# We can reshape tensor
# In this case 12 (1-d) -> (3,4) (2-d)
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
# giving -1, the exact number is calculated automatically
x.reshape(3, -1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
# torch.zeros make tensor which has 0 for it's all elements 
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# and torch.ones for 1
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
# make random number with mean of 0 and a s.d of 1
torch.randn((3,4))

tensor([[-0.1938,  1.0702, -0.1465,  0.8836],
        [ 1.1232, -0.3995,  1.2681,  0.1944],
        [-1.6402, -0.4705, -0.1768, -0.3157]])

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# concatenation with dim=0 is concatenation to row direction,
# and dim=1 to column direction

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
# Indexing is also available
X[1,2]

tensor(6.)